port: 8080
timeout: 300
proxies: http://127.0.0.1:7890
ja3: 771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-17513-21,29-23-24,0

mappers:
  - addr: https://gptscopilot.ai
    routes:
      - path: /gpts/proxies/v1/chat/completions
        rewrite: /api/chat/completions
        action:
          - '{{$var := rGet "Authorization"}}
             {{if contains $var "Bearer "}}
               {{$var = split $var " "}}
               {{$var = index $var 1}}
             {{end}}
             {{$var = append "__sid__=" $var}}
             {{rSet "cookie" $var}}
             {{rSet "origin" "https://gptscopilot.ai"}}
             {{rSet "referer" "https://gptscopilot.ai/gpts"}}
             {{rDel "Authorization"}}'
  - addr: https://api.openai.com
    routes:
      - path: /proxies/v1/chat/completions
        rewrite: /v1/chat/completions
  - addr: https://claude.ai
    ja3: true
    routes:
      - path: /api/organizations
      - path: /api/append_message
      - path: /api/retry_message