port: 8080
timeout: 300
proxies: http://127.0.0.1:7890
#proxies-pool: https://xxx.com
ja3: 771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-17513-21,29-23-24,0

mappers:
  # === newbing 代理 ===
  - addr: https://copilot.microsoft.com
    routes:
      - path: /copilot/turing/conversation/create
        rewrite: /turing/conversation/create
        action:
          - '{{req_setHeader "host" "sydney.bing.com"}}
             {{req_setHeader "origin" "https://copilot.microsoft.com"}}
             {{addr randomIp}}'
      - path: /copilot/images/kblob
        rewrite: /images/kblob
        action:
          - '{{req_setHeader "host" "sydney.bing.com"}}
             {{req_setHeader "origin" "https://copilot.microsoft.com"}}
             {{req_setHeader "referer" "https://copilot.microsoft.com"}}'
  - addr: https://www.bing.com
    routes:
      - path: /copilot/codex/plugins/available/get
        rewrite: /codex/plugins/available/get
  - addr: https://sydney.bing.com
    routes:
      - path: /sydney/ChatHub
        action:
          - '{{req_setHeader "host" "sydney.bing.com"}}
             {{req_setHeader "origin" "https://copilot.microsoft.com"}}
             {{addr randomIp}}'
  # === gptscopilot 代理 ===
  - addr: https://gptscopilot.ai
    routes:
      - path: /gpts/proxies/v1/chat/completions
        rewrite: /api/chat/completions
        action:
          - '{{$var := req_getHeader "Authorization"}}
             {{if contains $var "Bearer "}}
               {{$var = index (split $var " ") 1}}
             {{end}}
             {{$var = append "__sid__=" $var}}
             {{req_setHeader "cookie" $var}}
             {{req_setHeader "origin" "https://gptscopilot.ai"}}
             {{req_setHeader "referer" "https://gptscopilot.ai/gpts"}}
             {{req_delHeader "Authorization"}}'
  # === openai 代理 ===
  - addr: https://api.openai.com
    routes:
      - path: /proxies/v1/chat/completions
        rewrite: /v1/chat/completions
  # === claude 代理 ===
  - addr: https://claude.ai
    #proxies: auto
    ja3: true
    routes:
      - path: /claude/api/(.+)
        rewrite: /api/$1
  - addr: https://claude.ai
    static: true
    routes:
      - path: /_next/static
        action:
          - '{{req_setHeader "host" "claude.ai"}}
             {{req_setHeader "origin" "https://claude.ai"}}
             {{req_setHeader "referer" "https://claude.ai"}}'
        content:
          - '{{replaceAll "/api/" "/claude/api/"}}
             {{replaceAll "/chats" "/claude/chats"}}
             {{replaceAll "/chat/" "/claude/chat/"}}
             {{replaceAll "sw.js" "/claude/sw.js"}}
             {{replaceAll "/login" "/claude/login"}}
             {{replaceAll "/logout" "/claude/logout"}}
             {{replaceAll "settings/billing" "/claude/settings/billing"}}'
      - path: /cdn-cgi
        action:
          - '{{req_setHeader "host" "claude.ai"}}
             {{req_setHeader "origin" "https://claude.ai"}}
             {{req_setHeader "referer" "https://claude.ai"}}'
      - path: /images
      - path: /sentry
      - path: /manifest.json
        action:
          - '{{req_setHeader "host" "claude.ai"}}
             {{req_setHeader "origin" "https://claude.ai"}}
             {{req_setHeader "referer" "https://claude.ai"}}'
      - path: /claude/(.?)
        rewrite: /$1
        action:
          - '{{req_setHeader "host" "claude.ai"}}
             {{req_setHeader "origin" "https://claude.ai"}}
             {{req_setHeader "referer" "https://claude.ai"}}'
      - path: /claude$
        redirect: /claude/